import type { DateTime } from "luxon";
// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import React, { useContext, useState } from "react";
import MonthView from "~/components/monthView";
import { CurrentViewContext, DayBeingViewedContext } from "~/hooks/contexts";
import { useToday } from "~/hooks/useToday";

// import { api } from "~/utils/api";

export default function Home() {
  //const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const today = useToday();
  const [dayBeingViewed, setDayBeingViewed] = useState<DateTime<true>>(today);
  const [currentView, setCurrentView] = useState<"month" | "week" | "day">(
    "month",
  );

  return (
    <CurrentViewContext.Provider
      value={{ value: currentView, setValue: setCurrentView }}
    >
      <DayBeingViewedContext.Provider
        value={{ value: dayBeingViewed, setValue: setDayBeingViewed }}
      >
        <Head>
          <title>Calenduh</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <TopBar />
          <MonthView />
        </main>
      </DayBeingViewedContext.Provider>
    </CurrentViewContext.Provider>
  );
}

function TopBar() {
  const today = useToday();
  const { value: dayBeingViewed, setValue: setDayBeingViewed } = useContext(
    DayBeingViewedContext,
  );
  const { value: currentView, setValue: setCurrentView } =
    useContext(CurrentViewContext);
  return (
    <div className="flex flex-row justify-center gap-8">
      <h2
        onClick={() => {
          setDayBeingViewed(dayBeingViewed.minus({ month: 1 }));
        }}
        className="cursor-pointer"
      >
        {"<"}
      </h2>
      <h2>
        {dayBeingViewed.monthLong} {dayBeingViewed.year}
      </h2>
      <h2
        onClick={() => {
          setDayBeingViewed(dayBeingViewed.plus({ month: 1 }));
        }}
        className="cursor-pointer"
      >
        {">"}
      </h2>
      <h2
        onClick={() => {
          setDayBeingViewed(today);
        }}
        className="cursor-pointer underline"
      >
        Today
      </h2>
    </div>
  );
}
// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
