import { DateTime } from "luxon";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React, { useContext, useState } from "react";
import { Day } from "~/components/day";
import MonthView from "~/components/monthView";
import { CurrentViewContext, DayBeingViewedContext } from "~/hooks/contexts";
import { useToday } from "~/hooks/useToday";

import { api } from "~/utils/api";


export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const today = useToday();
  const [dayBeingViewed, setDayBeingViewed] = useState<DateTime<true>>(today);


  return (
    <CurrentViewContext.Provider value="month">
      <DayBeingViewedContext.Provider
        value={{ value: dayBeingViewed, setValue: setDayBeingViewed }}
      >
        <Head>
          <title>Calenduh</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MonthView />
      </DayBeingViewedContext.Provider>
    </CurrentViewContext.Provider>
  );
}


function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
