import { DateTime } from "luxon";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const today = DateTime.now();
  console.log(today);
  console.log(today.daysInMonth);
  const daysBeforeFirst = today.set({ day: 1 }).weekday;
  console.log(daysBeforeFirst);
  const daysAfterLast = 13 - today.set({ day: today.daysInMonth }).weekday;
  console.log(daysAfterLast);
  const daysInPreviousMonth = today.minus({ month: 1 }).daysInMonth;
  const daysInNextMonth = today.plus({ month: 1 }).daysInMonth;

  return (
    <>
      <Head>
        <title>Calenduh</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <div className="flex flex-row justify-center">
          {today.monthLong} {today.year}
        </div>
        <div className="grid grid-cols-7">
          <h2 className="">Sunday</h2>
          <h2 className="">Monday</h2>
          <h2 className="">Tuesday</h2>
          <h2 className="">Wednesday</h2>
          <h2 className="">Thursday</h2>
          <h2 className="">Friday</h2>
          <h2 className="">Saturday</h2>
        </div>
        <div className="grid grid-cols-7 grid-rows-6">
          {Array.from({ length: daysInPreviousMonth }, (_ , i) => i + 1)
            .slice(-daysBeforeFirst)
            .map((dayNumber) => (
              <Day currentMonth={false} key={dayNumber} dayNumber={dayNumber} />
            ))}
          {Array.from({ length: today.daysInMonth }, (_, i) => i + 1).map(
            (dayNumber) => (
              <Day key={dayNumber} dayNumber={dayNumber} />
            ),
          )}
          {Array.from({ length: daysInNextMonth }, (_, i) => i + 1)
            .slice(0, daysAfterLast)
            .map((dayNumber) => (
              <Day currentMonth={false} key={dayNumber} dayNumber={dayNumber} />
            ))}
        </div>
      </main>
    </>
  );
}

function Day({ currentMonth=true, dayNumber }: {currentMonth?:boolean, dayNumber: number }) {
  return (
    <div className={`h-32 border-4 border-black ${currentMonth? "text-black" : "text-red-600 font-bold"}`}>
      <h2 className="absolute">{dayNumber}</h2>
    </div>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
